# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               BOTS made for streamers
tagline:            
url:                 https://killertofus.github.io/docstest/
paginate:            1
baseurl:             '/poole/'

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              killer tofus
  url:               https://twitter.com/KillerofTofu
  discord:             killertofu#4612

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/killertofus/knarfbot
